var List_Random =
[
	{
		"attribute" : "Cute",
		"file_name" : "SP3S100448",
		"chr_id"    : "101",
		"chr_name"  : "島村卯月",
		"card_name" : "スマイル・アンド・トリート",
	},
	{
		"attribute" : "Cute",
		"file_name" : "SP3S100786",
		"chr_id"    : "103",
		"chr_name"  : "水本ゆかり",
		"card_name" : "想いのアンサンブル",
	},
	{
		"attribute" : "Cute",
		"file_name" : "SP3S100436",
		"chr_id"    : "106",
		"chr_name"  : "今井加奈",
		"card_name" : "メモリアルデイズ",
	},
	{
		"attribute" : "Cute",
		"file_name" : "SP3S100482",
		"chr_id"    : "108",
		"chr_name"  : "三村かな子",
		"card_name" : "新春の彩り",
	},
	{
		"attribute" : "Cute",
		"file_name" : "SP3S100468",
		"chr_id"    : "112",
		"chr_name"  : "緒方智絵里",
		"card_name" : "メリー・メリー・ホワイト",
	},
	{
		"attribute" : "Cute",
		"file_name" : "SP3S100897",
		"chr_id"    : "132",
		"chr_name"  : "小早川紗枝",
		"card_name" : "深紅の心化粧",
	},
	{
		"attribute" : "Cool",
		"file_name" : "SP3S200454",
		"chr_id"    : "188",
		"chr_name"  : "橘ありす",
		"card_name" : "ありすのティーパーティー",
	},
	{
		"attribute" : "Cool",
		"file_name" : "SP3S201275",
		"chr_id"    : "180",
		"chr_name"  : "佐々木千枝",
		"card_name" : "小さなマシェリ",
	},
	{
		"attribute" : "Cool",
		"file_name" : "SP3S201030",
		"chr_id"    : "184",
		"chr_name"  : "藤原肇",
		"card_name" : "びいどろの彩夏",
	},
	{
		"attribute" : "Cool",
		"file_name" : "SP3S201157",
		"chr_id"    : "219",
		"chr_name"  : "藤居朋",
		"card_name" : "サマータイム・ワンダー",
	},
	{
		"attribute" : "Cool",
		"file_name" : "SP3S200880",
		"chr_id"    : "233",
		"chr_name"  : "鷹富士茄子",
		"card_name" : "うたかたマーメイド",
	},
	{
		"attribute" : "Passion",
		"file_name" : "SP3S300798",
		"chr_id"    : "262",
		"chr_name"  : "依田芳乃",
		"card_name" : "はるべと咲くや",
	},
	{
		"attribute" : "Passion",
		"file_name" : "SP3S300412",
		"chr_id"    : "272",
		"chr_name"  : "十時愛梨",
		"card_name" : "プライベート・メイド",
	},
	{
		"attribute" : "Passion",
		"file_name" : "SP3S300598",
		"chr_id"    : "300",
		"chr_name"  : "イヴ・サンタクロース",
		"card_name" : "ミラクルホーリーナイト",
	},
	{
		"attribute" : "Passion",
		"file_name" : "SP3S301169",
		"chr_id"    : "309",
		"chr_name"  : "久川凪",
		"card_name" : "凪めく日々のおとぎ話",
	},
]